server:
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost
    username: root
    password: password1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
